name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["luajit"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master
      with:
        luarocksVersion: 3.12.2

    - name: install dependencies
      run: |
        luarocks install argparse
        luarocks install busted
        luarocks install moonscript
        luarocks install tableshape
        luarocks install luafilesystem
        luarocks install lua-cjson
        luarocks install lapis

    - name: build translations
      run: |
        moon build_translations.moon

    - name: test
      run: |
        busted -o utfTerminal

  notify:
    runs-on: ubuntu-latest
    environment: Notify
    needs:
      - test

    if: ${{ github.ref == 'refs/heads/master' && always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

